-- Schema for Locked In, dumped from the live Supabase project.
-- Generated by scripts/dump-schema.mjs via the Supabase Management API.
-- Run this in the SQL Editor of a fresh project, top to bottom.

-- Extensions ------------------------------------------------------------
create extension if not exists "pg_net" with schema "extensions";
create extension if not exists "pg_stat_statements" with schema "extensions";
create extension if not exists "pgcrypto" with schema "extensions";
create extension if not exists "supabase_vault" with schema "vault";
create extension if not exists "uuid-ossp" with schema "extensions";

-- Tables ----------------------------------------------------------------
create table public."chat_participants" (
  "room_id" uuid not null,
  "user_id" uuid not null,
  "joined_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "last_read_at" timestamp with time zone default timezone('utc'::text, now()),
  constraint "chat_participants_pkey" PRIMARY KEY (room_id, user_id)
);

create table public."chat_rooms" (
  "id" uuid default gen_random_uuid() not null,
  "is_group" boolean default false,
  "name" text,
  "created_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "created_by" uuid default auth.uid(),
  constraint "chat_rooms_pkey" PRIMARY KEY (id)
);

create table public."follows" (
  "follower_id" uuid not null,
  "following_id" uuid not null,
  "created_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint "follows_pkey" PRIMARY KEY (follower_id, following_id)
);

create table public."messages" (
  "id" uuid default gen_random_uuid() not null,
  "room_id" uuid not null,
  "sender_id" uuid not null,
  "content" text not null,
  "created_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "workout_id" uuid,
  "image_url" text,
  constraint "messages_pkey" PRIMARY KEY (id)
);

create table public."notification_preferences" (
  "user_id" uuid not null,
  "likes" boolean default true not null,
  "comments" boolean default true not null,
  "follows" boolean default true not null,
  "new_posts" boolean default true not null,
  "chats" boolean default true not null,
  "daily_roast" boolean default true not null,
  "push_enabled" boolean default true not null,
  "updated_at" timestamp with time zone default now() not null,
  constraint "notification_preferences_pkey" PRIMARY KEY (user_id)
);

create table public."notifications" (
  "id" uuid default gen_random_uuid() not null,
  "recipient_id" uuid not null,
  "type" text not null,
  "aggregation_key" text not null,
  "actor_count" integer default 1 not null,
  "last_actor_id" uuid,
  "workout_id" uuid,
  "comment_id" uuid,
  "preview" text,
  "read_at" timestamp with time zone,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "room_id" uuid,
  constraint "notifications_recipient_id_aggregation_key_key" UNIQUE (recipient_id, aggregation_key),
  constraint "notifications_pkey" PRIMARY KEY (id),
  constraint "notifications_type_check" CHECK ((type = ANY (ARRAY['like'::text, 'comment'::text, 'follow'::text, 'new_post'::text, 'chat'::text])))
);

create table public."profiles" (
  "id" uuid not null,
  "username" text,
  "display_name" text,
  "avatar_url" text,
  "created_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "expo_push_token" text,
  "bio" text,
  constraint "profiles_username_key" UNIQUE (username),
  constraint "profiles_pkey" PRIMARY KEY (id)
);

create table public."web_push_subscriptions" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "endpoint" text not null,
  "p256dh" text not null,
  "auth" text not null,
  "user_agent" text,
  "created_at" timestamp with time zone default now() not null,
  constraint "web_push_subscriptions_user_id_endpoint_key" UNIQUE (user_id, endpoint),
  constraint "web_push_subscriptions_pkey" PRIMARY KEY (id)
);

create table public."workout_comments" (
  "id" uuid default gen_random_uuid() not null,
  "workout_id" uuid not null,
  "user_id" uuid not null,
  "content" text not null,
  "created_at" timestamp with time zone default now() not null,
  constraint "workout_comments_pkey" PRIMARY KEY (id),
  constraint "workout_comments_content_check" CHECK (((length(content) >= 1) AND (length(content) <= 500)))
);

create table public."workout_likes" (
  "workout_id" uuid not null,
  "user_id" uuid not null,
  "created_at" timestamp with time zone default now() not null,
  constraint "workout_likes_pkey" PRIMARY KEY (workout_id, user_id)
);

create table public."workout_views" (
  "workout_id" uuid not null,
  "viewer_id" uuid not null,
  "viewed_at" timestamp with time zone default now() not null,
  constraint "workout_views_pkey" PRIMARY KEY (workout_id, viewer_id)
);

create table public."workouts" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "activity_type" text,
  "duration_minutes" integer not null,
  "notes" text,
  "image_url" text,
  "created_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "distance" text,
  "calories" integer default 0,
  constraint "workouts_pkey" PRIMARY KEY (id)
);

-- Foreign keys ----------------------------------------------------------
-- Separated from CREATE TABLE so the order tables are created in cannot
-- matter. Run after every table above exists.
alter table public."chat_participants" add constraint "chat_participants_room_id_fkey" FOREIGN KEY (room_id) REFERENCES chat_rooms(id) ON DELETE CASCADE;
alter table public."chat_participants" add constraint "chat_participants_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public."follows" add constraint "follows_follower_id_fkey" FOREIGN KEY (follower_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public."follows" add constraint "follows_following_id_fkey" FOREIGN KEY (following_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public."messages" add constraint "messages_room_id_fkey" FOREIGN KEY (room_id) REFERENCES chat_rooms(id) ON DELETE CASCADE;
alter table public."messages" add constraint "messages_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public."messages" add constraint "messages_workout_id_fkey" FOREIGN KEY (workout_id) REFERENCES workouts(id) ON DELETE CASCADE;
alter table public."notification_preferences" add constraint "notification_preferences_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public."notifications" add constraint "notifications_comment_id_fkey" FOREIGN KEY (comment_id) REFERENCES workout_comments(id) ON DELETE CASCADE;
alter table public."notifications" add constraint "notifications_last_actor_id_fkey" FOREIGN KEY (last_actor_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public."notifications" add constraint "notifications_recipient_id_fkey" FOREIGN KEY (recipient_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public."notifications" add constraint "notifications_room_id_fkey" FOREIGN KEY (room_id) REFERENCES chat_rooms(id) ON DELETE CASCADE;
alter table public."notifications" add constraint "notifications_workout_id_fkey" FOREIGN KEY (workout_id) REFERENCES workouts(id) ON DELETE CASCADE;
alter table public."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."web_push_subscriptions" add constraint "web_push_subscriptions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public."workout_comments" add constraint "workout_comments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public."workout_comments" add constraint "workout_comments_workout_id_fkey" FOREIGN KEY (workout_id) REFERENCES workouts(id) ON DELETE CASCADE;
alter table public."workout_likes" add constraint "workout_likes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public."workout_likes" add constraint "workout_likes_workout_id_fkey" FOREIGN KEY (workout_id) REFERENCES workouts(id) ON DELETE CASCADE;
alter table public."workout_views" add constraint "workout_views_viewer_id_fkey" FOREIGN KEY (viewer_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public."workout_views" add constraint "workout_views_workout_id_fkey" FOREIGN KEY (workout_id) REFERENCES workouts(id) ON DELETE CASCADE;
alter table public."workouts" add constraint "workouts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);

-- Indexes ---------------------------------------------------------------
CREATE INDEX notifications_recipient_idx ON public.notifications USING btree (recipient_id, created_at DESC);
CREATE INDEX notifications_unread_idx ON public.notifications USING btree (recipient_id) WHERE (read_at IS NULL);
CREATE INDEX web_push_subscriptions_user_idx ON public.web_push_subscriptions USING btree (user_id);
CREATE INDEX workout_comments_workout_idx ON public.workout_comments USING btree (workout_id, created_at);
CREATE INDEX workout_likes_user_idx ON public.workout_likes USING btree (user_id);
CREATE INDEX workout_likes_workout_idx ON public.workout_likes USING btree (workout_id);
CREATE INDEX workout_views_workout_idx ON public.workout_views USING btree (workout_id);

-- Functions -------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.actor_name(p_user_id uuid)
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select coalesce(display_name, username, 'Someone')
  from public.profiles
  where id = p_user_id;
$function$
;

CREATE OR REPLACE FUNCTION public.get_my_chat_rooms()
 RETURNS SETOF uuid
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  select room_id from public.chat_participants where user_id = auth.uid();
$function$
;

CREATE OR REPLACE FUNCTION public.notif_pref(p_user_id uuid, p_pref text)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_value boolean;
begin
  execute format('select %I from notification_preferences where user_id = $1', p_pref)
    into v_value
    using p_user_id;
  return coalesce(v_value, true);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.on_follow()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_actor text;
begin
  if new.follower_id = new.following_id then return new; end if;
  if not public.notif_pref(new.following_id, 'follows') then return new; end if;

  perform public.upsert_notification(
    new.following_id, 'follow', 'follow:' || new.follower_id::text,
    new.follower_id, null, null, null
  );

  v_actor := public.actor_name(new.follower_id);
  perform public.send_push_notification(
    new.following_id,
    'Locked In',
    v_actor || ' started following you',
    jsonb_build_object('type', 'follow', 'actor_id', new.follower_id)
  );
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.on_message_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  r record;
  v_preview text;
  v_actor text;
begin
  if new.content is not null and length(new.content) > 0 then
    v_preview := left(new.content, 80);
  elsif new.image_url is not null then
    v_preview := '📷 Photo';
  elsif new.workout_id is not null then
    v_preview := '🏋️ Shared a workout';
  else
    v_preview := 'New message';
  end if;

  v_actor := public.actor_name(new.sender_id);

  for r in
    select user_id from public.chat_participants
    where room_id = new.room_id and user_id <> new.sender_id
  loop
    if public.notif_pref(r.user_id, 'chats') then
      perform public.upsert_chat_notification(
        r.user_id,
        'chat:' || new.room_id::text || ':' || new.sender_id::text,
        new.sender_id, new.room_id, v_preview
      );
      perform public.send_push_notification(
        r.user_id,
        v_actor,
        v_preview,
        jsonb_build_object('type', 'chat', 'room_id', new.room_id, 'actor_id', new.sender_id)
      );
    end if;
  end loop;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.on_workout_comment()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_owner_id uuid;
  v_actor    text;
begin
  select user_id into v_owner_id from public.workouts where id = new.workout_id;
  if v_owner_id is null or v_owner_id = new.user_id then return new; end if;
  if not public.notif_pref(v_owner_id, 'comments') then return new; end if;

  perform public.upsert_notification(
    v_owner_id, 'comment',
    'comment:' || new.workout_id::text || ':' || new.user_id::text,
    new.user_id, new.workout_id, new.id, left(new.content, 80)
  );

  v_actor := public.actor_name(new.user_id);
  perform public.send_push_notification(
    v_owner_id,
    v_actor,
    'commented: ' || left(new.content, 100),
    jsonb_build_object('type', 'comment', 'workout_id', new.workout_id, 'comment_id', new.id, 'actor_id', new.user_id)
  );
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.on_workout_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  r record;
  v_actor text;
begin
  v_actor := public.actor_name(new.user_id);
  for r in
    select follower_id from public.follows where following_id = new.user_id
  loop
    if public.notif_pref(r.follower_id, 'new_posts') then
      perform public.upsert_notification(
        r.follower_id, 'new_post', 'post:' || new.id::text,
        new.user_id, new.id, null, null
      );
      perform public.send_push_notification(
        r.follower_id,
        'Locked In',
        v_actor || ' posted a new workout',
        jsonb_build_object('type', 'new_post', 'workout_id', new.id, 'actor_id', new.user_id)
      );
    end if;
  end loop;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.on_workout_like()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_owner_id uuid;
  v_actor    text;
begin
  select user_id into v_owner_id from public.workouts where id = new.workout_id;
  if v_owner_id is null or v_owner_id = new.user_id then return new; end if;
  if not public.notif_pref(v_owner_id, 'likes') then return new; end if;

  perform public.upsert_notification(
    v_owner_id, 'like', 'like:' || new.workout_id::text,
    new.user_id, new.workout_id, null, null
  );

  v_actor := public.actor_name(new.user_id);
  perform public.send_push_notification(
    v_owner_id,
    'Locked In',
    v_actor || ' liked your workout',
    jsonb_build_object('type', 'like', 'workout_id', new.workout_id, 'actor_id', new.user_id)
  );
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.on_workout_unlike()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_owner_id    uuid;
  v_other_count int;
begin
  select user_id into v_owner_id from public.workouts where id = old.workout_id;
  if v_owner_id is null or v_owner_id = old.user_id then
    return old;
  end if;

  -- Are there other likes on this post?
  select count(*) into v_other_count
    from public.workout_likes
    where workout_id = old.workout_id and user_id <> old.user_id;

  if v_other_count = 0 then
    delete from public.notifications
      where recipient_id = v_owner_id
        and aggregation_key = 'like:' || old.workout_id::text;
  else
    -- Just decrement the count; pick a remaining liker to display
    update public.notifications
      set actor_count = greatest(actor_count - 1, 1),
          last_actor_id = (
            select user_id from public.workout_likes
            where workout_id = old.workout_id and user_id <> old.user_id
            order by created_at desc limit 1
          ),
          updated_at = now()
      where recipient_id = v_owner_id
        and aggregation_key = 'like:' || old.workout_id::text;
  end if;

  return old;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.send_push_notification(p_recipient_id uuid, p_title text, p_body text, p_data jsonb DEFAULT '{}'::jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
declare
  v_expo_token text;
  v_push_enabled boolean;
begin
  -- Master push toggle from notification_preferences. Defaults to true if no row.
  select coalesce(push_enabled, true) into v_push_enabled
    from public.notification_preferences
    where user_id = p_recipient_id;
  if v_push_enabled is null then v_push_enabled := true; end if;
  if not v_push_enabled then return; end if;

  select expo_push_token into v_expo_token
    from public.profiles
    where id = p_recipient_id;

  if v_expo_token is null or length(v_expo_token) = 0 then
    return;
  end if;

  perform net.http_post(
    url := 'https://exp.host/--/api/v2/push/send',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Accept', 'application/json',
      'Accept-encoding', 'gzip, deflate'
    ),
    body := jsonb_build_object(
      'to', v_expo_token,
      'sound', 'default',
      'title', p_title,
      'body', p_body,
      'data', p_data,
      'priority', 'high',
      'channelId', 'default'
    )
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.upsert_chat_notification(p_recipient_id uuid, p_aggregation_key text, p_actor_id uuid, p_room_id uuid, p_preview text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.notifications
    (recipient_id, type, aggregation_key, actor_count, last_actor_id,
     room_id, preview, created_at, updated_at)
  values
    (p_recipient_id, 'chat', p_aggregation_key, 1, p_actor_id,
     p_room_id, p_preview, now(), now())
  on conflict (recipient_id, aggregation_key) do update
    set actor_count   = notifications.actor_count + 1,
        last_actor_id = excluded.last_actor_id,
        preview       = excluded.preview,           -- show the latest message
        read_at       = null,
        updated_at    = now();
end;
$function$
;

CREATE OR REPLACE FUNCTION public.upsert_notification(p_recipient_id uuid, p_type text, p_aggregation_key text, p_actor_id uuid, p_workout_id uuid, p_comment_id uuid, p_preview text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.notifications
    (recipient_id, type, aggregation_key, actor_count, last_actor_id,
     workout_id, comment_id, preview, created_at, updated_at)
  values
    (p_recipient_id, p_type, p_aggregation_key, 1, p_actor_id,
     p_workout_id, p_comment_id, p_preview, now(), now())
  on conflict (recipient_id, aggregation_key) do update
    set actor_count   = case
                          when notifications.last_actor_id = excluded.last_actor_id
                            then notifications.actor_count
                          else notifications.actor_count + 1
                        end,
        last_actor_id = excluded.last_actor_id,
        comment_id    = coalesce(excluded.comment_id, notifications.comment_id),
        preview       = coalesce(excluded.preview, notifications.preview),
        read_at       = null,                  -- mark unread again on new activity
        updated_at    = now();
end;
$function$
;

-- Triggers --------------------------------------------------------------
CREATE TRIGGER trg_on_follow AFTER INSERT ON public.follows FOR EACH ROW EXECUTE FUNCTION on_follow();
CREATE TRIGGER trg_on_message_insert AFTER INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION on_message_insert();
CREATE TRIGGER trg_on_workout_comment AFTER INSERT ON public.workout_comments FOR EACH ROW EXECUTE FUNCTION on_workout_comment();
CREATE TRIGGER trg_on_workout_like AFTER INSERT ON public.workout_likes FOR EACH ROW EXECUTE FUNCTION on_workout_like();
CREATE TRIGGER trg_on_workout_unlike AFTER DELETE ON public.workout_likes FOR EACH ROW EXECUTE FUNCTION on_workout_unlike();
CREATE TRIGGER trg_on_workout_insert AFTER INSERT ON public.workouts FOR EACH ROW EXECUTE FUNCTION on_workout_insert();

-- Row-level security ----------------------------------------------------
alter table public."chat_participants" enable row level security;
alter table public."chat_rooms" enable row level security;
alter table public."follows" enable row level security;
alter table public."messages" enable row level security;
alter table public."notification_preferences" enable row level security;
alter table public."notifications" enable row level security;
alter table public."profiles" enable row level security;
alter table public."web_push_subscriptions" enable row level security;
alter table public."workout_comments" enable row level security;
alter table public."workout_likes" enable row level security;
alter table public."workout_views" enable row level security;
alter table public."workouts" enable row level security;

create policy "Users can add participants" on public."chat_participants"
  as permissive
  for insert
  to public
  with check (true);

create policy "Users can update their own read status" on public."chat_participants"
  as permissive
  for update
  to public
  using ((user_id = auth.uid()));

create policy "Users can view participants of their rooms" on public."chat_participants"
  as permissive
  for select
  to public
  using ((room_id IN ( SELECT get_my_chat_rooms() AS get_my_chat_rooms)));

create policy "Creators can view their own rooms" on public."chat_rooms"
  as permissive
  for select
  to public
  using ((auth.uid() = created_by));

create policy "Users can create rooms" on public."chat_rooms"
  as permissive
  for insert
  to public
  with check (true);

create policy "Users can delete rooms they are in" on public."chat_rooms"
  as permissive
  for delete
  to public
  using ((EXISTS ( SELECT 1
   FROM chat_participants
  WHERE ((chat_participants.room_id = chat_rooms.id) AND (chat_participants.user_id = auth.uid())))));

create policy "Users can view rooms they are in" on public."chat_rooms"
  as permissive
  for select
  to public
  using ((EXISTS ( SELECT 1
   FROM chat_participants
  WHERE ((chat_participants.room_id = chat_rooms.id) AND (chat_participants.user_id = auth.uid())))));

create policy "Follows are viewable by everyone." on public."follows"
  as permissive
  for select
  to public
  using (true);

create policy "Users can follow others." on public."follows"
  as permissive
  for insert
  to public
  with check ((auth.uid() = follower_id));

create policy "Users can unfollow." on public."follows"
  as permissive
  for delete
  to public
  using ((auth.uid() = follower_id));

create policy "Users can read messages in their rooms" on public."messages"
  as permissive
  for select
  to public
  using ((EXISTS ( SELECT 1
   FROM chat_participants
  WHERE ((chat_participants.room_id = messages.room_id) AND (chat_participants.user_id = auth.uid())))));

create policy "Users can send messages to their rooms" on public."messages"
  as permissive
  for insert
  to public
  with check (((EXISTS ( SELECT 1
   FROM chat_participants
  WHERE ((chat_participants.room_id = messages.room_id) AND (chat_participants.user_id = auth.uid())))) AND (auth.uid() = sender_id)));

create policy "users insert their own prefs" on public."notification_preferences"
  as permissive
  for insert
  to authenticated
  with check ((auth.uid() = user_id));

create policy "users read their own prefs" on public."notification_preferences"
  as permissive
  for select
  to authenticated
  using ((auth.uid() = user_id));

create policy "users update their own prefs" on public."notification_preferences"
  as permissive
  for update
  to authenticated
  using ((auth.uid() = user_id));

create policy "users delete their own notifications" on public."notifications"
  as permissive
  for delete
  to authenticated
  using ((auth.uid() = recipient_id));

create policy "users see their own notifications" on public."notifications"
  as permissive
  for select
  to authenticated
  using ((auth.uid() = recipient_id));

create policy "users update their own notifications" on public."notifications"
  as permissive
  for update
  to authenticated
  using ((auth.uid() = recipient_id));

create policy "Public profiles are viewable by everyone." on public."profiles"
  as permissive
  for select
  to public
  using (true);

create policy "Users can insert their own profile." on public."profiles"
  as permissive
  for insert
  to public
  with check ((auth.uid() = id));

create policy "Users can update own profile." on public."profiles"
  as permissive
  for update
  to public
  using ((auth.uid() = id));

create policy "users manage their own web subs" on public."web_push_subscriptions"
  as permissive
  for all
  to authenticated
  using ((auth.uid() = user_id))
  with check ((auth.uid() = user_id));

create policy "anyone authenticated can read comments" on public."workout_comments"
  as permissive
  for select
  to authenticated
  using (true);

create policy "users can comment on their own behalf" on public."workout_comments"
  as permissive
  for insert
  to authenticated
  with check ((auth.uid() = user_id));

create policy "users can delete their own comments" on public."workout_comments"
  as permissive
  for delete
  to authenticated
  using ((auth.uid() = user_id));

create policy "anyone authenticated can read likes" on public."workout_likes"
  as permissive
  for select
  to authenticated
  using (true);

create policy "users can like on their own behalf" on public."workout_likes"
  as permissive
  for insert
  to authenticated
  with check ((auth.uid() = user_id));

create policy "users can unlike their own likes" on public."workout_likes"
  as permissive
  for delete
  to authenticated
  using ((auth.uid() = user_id));

create policy "owner sees full view list" on public."workout_views"
  as permissive
  for select
  to authenticated
  using (((auth.uid() = viewer_id) OR (auth.uid() = ( SELECT workouts.user_id
   FROM workouts
  WHERE (workouts.id = workout_views.workout_id)))));

create policy "users record their own views" on public."workout_views"
  as permissive
  for insert
  to authenticated
  with check ((auth.uid() = viewer_id));

create policy "Anyone logged in can see workouts" on public."workouts"
  as permissive
  for select
  to authenticated
  using (true);

create policy "Users can delete their own workouts." on public."workouts"
  as permissive
  for delete
  to public
  using ((auth.uid() = user_id));

create policy "Users can insert their own workouts" on public."workouts"
  as permissive
  for insert
  to authenticated
  with check ((auth.uid() = user_id));

create policy "Users can insert their own workouts." on public."workouts"
  as permissive
  for insert
  to public
  with check ((auth.uid() = user_id));

create policy "Users can update their own workouts." on public."workouts"
  as permissive
  for update
  to public
  using ((auth.uid() = user_id));

create policy "Workouts are viewable by everyone." on public."workouts"
  as permissive
  for select
  to public
  using (true);

-- Realtime --------------------------------------------------------------
-- Realtime is opt-in per table through this publication.
alter publication supabase_realtime add table public."chat_participants";
alter publication supabase_realtime add table public."messages";
alter publication supabase_realtime add table public."notifications";

-- 12 tables, 36 policies, 6 triggers, 12 functions.
